""" 
                                        Iniciacion de variables
password->string
iniciarPrograma->bool
ch->string
command->string
usuarioAdmin->string
constraseñaAdmin->string
novedad1->string
novedad2->string
novedad3->string
intentos->int
usuario->string
contraseña->string
menuAdministrador->bool
linea->string
opcion->int
gestionAerolineas->bool
nombre->string
codigo->string
descripcion->string
pais->string
seguir->bool
arg->int
bra->int
chi->int
continuar->string
pais_mayor->string
mayor_cantidad->int
pais_menor->string
menor_cantidad->int
gestionNovedades->bool
codigo->string
nuevo_texto->string
"""